---
- name: apt install pip
  sudo: yes
  apt: name={{ item }} state=present update_cache=true
  with_items:
   - python-pip
  when: ansible_pkg_mgr == 'apt'

- name: install httplib2 prereq - required by URI module
  sudo: yes
  pip: name=httplib2

- name: create target app dir
  sudo: yes
  file: path=/apps state=directory owner=vagrant group=vagrant

- name: create apps/logs
  file: name=/apps/logs state=directory

- name: Transfer build package
  copy: src=artifacts/hello_world/{{ app_jar }} dest=/apps/{{ app_jar }}

- name: Transfer config file
  copy: src=artifacts/hello_world/dev_config.yml dest={{ app_config_filepath }}

- name: Create upstart daemon script
  sudo: yes
  template: src=dropwizard_upstart.j2 dest=/etc/init/hello-world.conf owner=root group=root mode=0644

- name: Start thing
  sudo: yes
  service: name=hello-world state=started

- name: wait up to 15 seconds for port 8080 to become available
  wait_for: port=8080 timeout=15

- name: hit the app end-point
  uri: url=http://localhost:8080/helloworld
